### PR TITLE
Updated to support flash player versions older then 11.0.

### PR DESCRIPTION
**Pull request by st3v0**
The following changes have been made:
- Updated `generateUUID` to use the `crypto.generateRandomBytes` class instead of `flash.crypto.generateRandomBytes`
- Changed the internal crypto library to check for the flash crypto library. If it's missing then it will fallback to using the old pseudorandom generator method.

Please Review.

### CODE REVIEW

**Comment by zwetan** [comment]
No, can not work like that.

The way it's done is not ideal but is more related to the Redtamarin API than the Flash API.

`crypto.generateRandomBytes` in Redtamarin is a dirty hack and slow and temporary
in the future Redtamarin will implement a native function defined in `flash.crypto.generateRandomBytes` and `crypto.generateRandomBytes` will just be removed/deprecated.

The point is that "as is" your patch work within the logic of the Flash API
but will break when compiled with Redtamarin API.

Also `/dev/urandom` is secure while `Math.random()` is not.

**Comment by caseyryan** [comment]
comment moved to issue #18

**Comment by st3v0** [comment]
Hmm, I see where you're coming from. Unfortunately using any type of client-base RNG will not protect against collisions, the only way to solve that would be to have a server based token generator.

Perhaps a better solution to this problem would be too allow consumers of this library to set their own clientId, perhaps via `config.overrideClientId`. There would of course need to be a Client Id Validator built to protect from invalid inputs. If this property is configured then the tracker would bypass executing the `generateUUID()`. This will allow consumers whom have a server based token generator to track players across multiple devices. 

This of course doesn't solve the backwards compatibility problem, however it would allow older flash players to function as long as consumers override the client id.

Would you be happy with this type of solution?

**Comment by zwetan** [comment]
We follow the Measurement Protocol documentation
[Client ID](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#cid)

> The value of this field should be a random UUID (version 4) as described in http://www.ietf.org/rfc/rfc4122.txt

see also doc for [flash.crypto.generateRandomBytes](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/crypto/package.html#generateRandomBytes%28%29)

> The random sequence is generated using cryptographically strong functions provided by the operating system. If the appropriate function is not available on an individual client computer or device, then an error is thrown.

the workaround for the command-line client use `/dev/urandom` which is considered a high quality random number generator
[uuid_generate_random](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/uuid_generate_random.3.html)

that said even urandom can have issues
[A good idea with bad usage: /dev/urandom](http://insanecoding.blogspot.fr/2014/05/a-good-idea-with-bad-usage-devurandom.html)

but in a next implementation of Redtamarin runtime we will use a native function to use "cryptographically strong functions provided by the operating system"

so for the time being it is good enough

which basically left one use case: AIR 2.6 under Linux
current workaround would be to fall back to what gaforflash was doing
see [The simplest possible Tracker - The Client ID](https://github.com/zwetan/as3-universal-analytics/wiki/SimplestTracker#the-client-id)

not ideal

``` as3
function getClientID():Number
{
    var cid:Number = (generate32bitRandom() ^ generateUserDataHash()) * 0x7fffffff;
    return cid;
}
```

but it was good enough and worked for years with gaforflash

**Pull request closed without merging**
