### PR TITLE
Added an extra Helper method to the Tracker and patched a HitSender Loader issue.

### PR DESCRIPTION
**Pull request by st3v0**
I've made the following changes:
- Added `addOneTime` helper method to the Tracker to keep it consistent with the `setOneTime` method.
- Updated the Loader HitSenders to fix an issue when communicating simultaneous requests causes the last load operation to close. This would result in events not being communicated to analytics services.

Please Review.

### CODE REVIEW

**Comment by zwetan** [comment]
Hi st3v0, thanks for the contrib

For info, the source repository is a private svn that I mirror on github
so I can not directly merge a pull request, but I took your patch and rebased with `--use-log-author`
and as you can see here
https://github.com/zwetan/as3-universal-analytics/commit/244b1e49e382d76c9202c3be69cee3aa40787217

the merge went without a glitch :)

**Comment by st3v0** [comment]
That's awesome, when are you planning on release 0.9.0?

**Comment by zwetan** [comment]
it should be this week

**Comment by pixelthis-peter** [comment]
Thanks for the library! Does the latest code (https://github.com/zwetan/as3-universal-analytics) contain this fix?

**Comment by zwetan** [comment]
not yet, will be integrated in v0.9

**Comment by 22Round** [comment]
Hi @zwetan when would be v0.9 available?

**Comment by zwetan** [comment]
I know it seems something that take forever but I'm really busy on other things, so yeah I'm pretty much late for this v0.9.

If it was not clear the change from this pull request are already merged in the code base, while v0.9 is not available yet, you can build the project with the latest change, see [HOW TO Build](https://github.com/zwetan/as3-universal-analytics/wiki/HOWTOBuild).

**Pull request closed without merging**
